In [2]:
import torch

X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]])


In [4]:
print(X, Y)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]) tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]])


In [3]:
torch.cat((X, Y), dim = 0)


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 1.,  2.,  3.,  4.],
        [ 1.,  2.,  3.,  4.],
        [ 1.,  2.,  3.,  4.]])

# p7 数据操作实现

In [7]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
x.shape

torch.Size([12])

In [11]:
x.numel()

12

重新换形状

In [13]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
torch.zeros((2, 3, 4))

In [3]:
torch.tensor([[1.0, 2], [2, 2]])

tensor([[1., 2.],
        [2., 2.]])

In [5]:
torch.arange(12, dtype=torch.float32)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [6]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))

In [8]:
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  2.,  3.,  4.],
         [ 1.,  2.,  3.,  4.],
         [ 1.,  2.,  3.,  4.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  1.,  2.,  3.,  4.]]))

In [10]:
Y.sum()

tensor(30)

广播机制

In [11]:
a = torch.arange(2).reshape(1,2)
b = torch.arange(3).reshape(3,1)
a, b

(tensor([[0, 1]]),
 tensor([[0],
         [1],
         [2]]))

In [12]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [13]:
# 
before = id(Y)
Y = Y + X
id(Y) == before


False

In [16]:
z = torch.zeros_like(Y)
print(id(z))
z[:] = X + Y
print(id(z))
z = X + Y
print(id(z))

4782619632
4782619632
4777881968


In [17]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [18]:
import os
os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file = os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n')#列名
    f.write('NA,Pave,127500\n')#每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [20]:
import pandas as pd

data = pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [26]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]

# 确保 inputs 只包含数值列
inputs = inputs.select_dtypes(include=['number'])

# 填充 NaN 值
inputs = inputs.fillna(inputs.mean())

# 输出调试信息
print(inputs.dtypes)  # 确保都是数值类型
print(inputs.head())  # 观察数据是否正确填充


NumRooms    float64
dtype: object
   NumRooms
0       3.0
1       2.0
2       4.0
3       3.0


In [30]:
import torch

a = torch.ones((2, 5, 4))
a

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

axis等于几,就是从第几个纬度来求和

In [35]:
a.shape

torch.Size([2, 5, 4])

In [38]:
a.sum(axis=0).shape

torch.Size([5, 4])

In [36]:
a.sum(axis=1).shape

torch.Size([2, 4])

In [37]:
a.sum(axis=2).shape

torch.Size([2, 5])

In [34]:
# a.sum(axis=0)
# a.sum(axis=1)
a.sum(axis=2)

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [39]:
a.sum(axis=2)

tensor([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]])

In [40]:
a.sum(axis=1, keepdims=True).shape

torch.Size([2, 1, 4])